# Generated by Django 3.2.3 on 2021-07-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGREEMENTID', models.CharField(max_length=50, unique=True)),
                ('CUSTOMERNAME', models.CharField(max_length=50)),
                ('COMPANY', models.CharField(max_length=50)),
                ('BKT', models.IntegerField()),
                ('LAST_MONTH', models.CharField(max_length=50)),
                ('MOB', models.IntegerField(null=True)),
                ('TOTAL_COLLECTABLE', models.IntegerField(null=True)),
                ('POS', models.IntegerField()),
                ('EMI', models.IntegerField()),
                ('FOS', models.CharField(max_length=50)),
                ('TL', models.CharField(max_length=30)),
                ('TC_NAME', models.CharField(max_length=30)),
                ('LOAN_TYPE', models.CharField(max_length=6, null=True)),
                ('STATE', models.CharField(max_length=30)),
                ('AREA', models.CharField(max_length=30)),
                ('BOUNCING_REASONS', models.CharField(max_length=30, null=True)),
                ('EMI_CYCLE', models.IntegerField(null=True)),
                ('LOAN_AMT', models.IntegerField(null=True)),
                ('ADDITIONAL_NUMBER', models.IntegerField(null=True)),
                ('upload', models.FileField(upload_to='media/L_T/L_T Allocation %d %m %y')),
            ],
        ),
        migrations.CreateModel(
            name='loginpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('Emp_ID', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Paid_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('PROCESS', models.CharField(max_length=50)),
                ('AGREEMENTID', models.CharField(max_length=50)),
                ('CUSTOMERNAME', models.CharField(max_length=50)),
                ('MODE', models.CharField(max_length=50)),
                ('EMI', models.IntegerField()),
                ('PAID_AMOUNT', models.IntegerField()),
                ('BOUNCING_AMOUNT', models.IntegerField()),
                ('AGAINST', models.CharField(max_length=50)),
                ('FOS', models.CharField(max_length=50)),
                ('BKT', models.IntegerField()),
                ('upload', models.FileField(upload_to='media/L_T/L_T PAID FILE %d %m %y')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('confirm_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('confirm_password', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Emp_ID', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
